### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ksherlock** [ksherlock/ample#1]
- [ ] include mame executable, sdl libraries, etc so everything it's self contained. Should also have an option to use the system version of mame.
- [ ] automatically download relevant ROMs from internet archive (https://archive.org/download/MAME223RomsOnlyMerged)
- [ ] resize window to fit on 13" MacBook
- [ ] machine information is currently hard-coded (via a python script that simplifies `mame -listxml` to a plist).  This should probably be moved to objective C and handled real-time to match system mame's options
- [ ] drag-n-drop disk image order
- [ ] Window for a library of recently used disk images
- [ ] Or perhaps, like Sweet-16, use Finder as the disk image manager and have a Open Disk Images Folder menu
- [ ] Some cards - SSC and more importantly Apple SCSI have child slots.  Consider moving slots to a tree view to incorporate them.  (Apple SCSI child slots enable more hard disk images but are off by default)
- [ ] Split up media by slot? This would also make it easier to use the allowed file types.

**Comment by HelixNRG** [comment]
I know it's only early days for Ample, but would it be possible to implement the VGM mod as part of the frontend as well as what you're hoping to bundle to make installation as easy as possible?

Details on the VGM Mod for MAME: https://vgmrips.net/wiki/MAME/MESS_VGM_mod

Details on VGM format: https://vgmrips.net/wiki/VGM_File_Format

I'm keen to record VGM rips from IIGS games, I don't yet know how to edit them into nice, clean presentable music tracks (yet) but having in the frontend would make it easy to start.

Some rips of IIGS music from games have already been made and I've put them into a playlist: https://vgmrips.net/packs/playlist/252

**Comment by ksherlock** [comment]
I am interested in VGM Rip support and have been for a number of years, in fact.  The most recent VGM patches seem to be a couple years old.  If I can build it without too much work, I'll probably include it. 

https://vgmrips.net/forum/viewtopic.php?f=3&t=106

**Comment by HelixNRG** [comment]
Fingers are crossed. Hope it's easy to implement.

**Comment by ksherlock** [comment]
[Release 5](https://github.com/ksherlock/ample/releases/tag/release-5) has VGM support.

**Comment by HelixNRG** [comment]
Would MAME have the ability to remember BRAM settings between sessions? Or does MAME support save states, that could work just as well (?) as remembering BRAM settings?

**Comment by ksherlock** [comment]
It looks like MAME does store (and restore) BRAM.  Check out the nvram directory in ~/Library/Application Support/Ample/.

**Comment by ksherlock** [comment]
I've never tried it but mame does have save states.  Enter partial UI mode (delete key) and use Shift-F7 to create a save state and F7 to load a save state.

**Comment by HelixNRG** [comment]
When bookmarking of System configurations is added, if that could automagically include the NVRAM settings, along with the system, expansion cards, disk images allocated to slots, graphics settings, etc. that'd be the ticket.
